### ISSUE TITLE
Is it possible to get account games?

### ISSUE THREAD

**Issue by vega0** [SD4RK/epicstore_api#12]
Qestion in the title.

**Comment by SD4RK** [comment]
It's possible, but not now. At the moment library does not support authorized requests. You can only do some public ones that you are able to execute withouth any authorization.
In order to get account games you may take a look at [this](https://github.com/derrod/legendary). Or you may intercept the traffic of the Epic Games Store by yourself and mimic its requests.

I'll implement the authorized requests, but do not know when, I do not have much motivation to do so and it requires a lot of work. But any pull requests are welcome.

**Comment by vega0** [comment]
> It's possible, but not now. At the moment library does not support authorized requests. You can only do some public ones that you are able to execute withouth any authorization.
> In order to get account games you may take a look at [this](https://github.com/derrod/legendary). Or you may intercept the traffic of the Epic Games Store by yourself and mimic its requests.
> 
> I'll implement the authorized requests, but do not know when, I do not have much motivation to do so and it requires a lot of work. But any pull requests are welcome.

So it's possible to fetch owned games of another accounts, not main?

**Comment by SD4RK** [comment]
> So it's possible to fetch owned games of another accounts, not main? I asking cuz i've no default interface (in epic games launcher) to see what games owned of my friends, i guess it's not possible

Oh, if you mean other accounts, then the answer is definetely no. You can only fetch owned games of account you're currently logged in. But still, even that functionality is not available in the library at the moment.

**Comment by vega0** [comment]
> > So it's possible to fetch owned games of another accounts, not main? I asking cuz i've no default interface (in epic games launcher) to see what games owned of my friends, i guess it's not possible
> 
> Oh, if you mean other accounts, then the answer is definetely no. You can only fetch owned games of account you're currently logged in. But still, even that functionality is not available in the library at the moment.

Okay
