### ISSUE TITLE
How to remove from free games list?

### ISSUE THREAD

**Issue by LrdOfDarkness** [SD4RK/epicstore_api#5]
Hi,
I'm quite new to coding and stuff, but I want to learn it by coding small things and reading other people's codes. I used your example code to create a discord bot that sends the new free games, but now I have the problem, that it always sends previous free games, that are no longer free. I tried different things like `free_games.remove(game)` at the end of the "for game in free_games" function, but than i get only previous free games but not the current. I also tried `free_games.clear()` but it didn't work aswell. Can you give me some tips? :D

**Comment by SD4RK** [comment]
Hello,
So, if you want to do a bot that will be used to notify whatever a new free game is came out then I'd recommend to create some kinda database (you can just use a .json file or an actual database, doesn't matter) to identify free games that bot has already sent, then just repeat this task once a day or once a week (your choice). To identify the games you can use `id` field in `game` json object. Otherwise, if your bot is serving forever, you can use a temporary database, e.g. just a Python's list of game ids' that already be sent and then just check that the current game's id we're iterating through is not in that list.
And a little of off-topic. I do not recommend to use this library with d.py, because it's an async library, when this library is built using synchronous `requests`.
